/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#9d4300",
        "primary-container": "#f97316",
        "primary-fixed": "#ffdbca",
        "on-primary": "#ffffff",
        "on-primary-container": "#582200",
        secondary: "#a73a00",
        "secondary-container": "#fd651e",
        tertiary: "#6B7280",
        "tertiary-container": "#919bad",
        surface: "#f9f9ff",
        "surface-canvas": "#F5F6F8",
        "surface-card": "#FFFFFF",
        "surface-container-low": "#f0f3ff",
        "surface-container": "#e7eefe",
        "surface-container-high": "#e2e8f8",
        "surface-variant": "#dce2f3",
        "on-surface": "#151c27",
        "on-surface-variant": "#584237",
        "border-subtle": "#E5E7EB",
        "status-success": "#16A34A",
        "status-danger": "#DC2626",
        "status-warning": "#F59E0B",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      fontFamily: { sans: ["Inter", "system-ui", "sans-serif"] },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-md": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "title-sm": ["16px", { lineHeight: "22px", fontWeight: "600" }],
        "price-lg": ["18px", { lineHeight: "24px", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "26px", fontWeight: "600" }],
        "headline-lg": ["26px", { lineHeight: "32px", fontWeight: "700" }],
        "display-stat": ["30px", { lineHeight: "38px", fontWeight: "700" }],
        "receipt-mono": ["13px", { lineHeight: "18px", fontWeight: "500" }],
      },
      borderRadius: { DEFAULT: "0.5rem", lg: "0.75rem", xl: "1rem", "2xl": "1.5rem" },
      spacing: {
        "space-xs": "0.25rem", "space-sm": "0.5rem", "space-md": "1rem",
        "space-lg": "1.5rem", "space-xl": "2rem", gutter: "1rem",
        "gutter-lg": "1.5rem", margin: "1.25rem", "margin-mobile": "0.75rem",
      },
    },
  },
  plugins: [],
};
